### PR TITLE
wait for artifact uploading (fixes #73)

### LINKED ISSUE #73: java.util.zip.ZipException: error in opening zip file
Jenkins: 2.42
Allure Core: 1.5.0
Allure Jenkins plugin: 2.11
Jenkins Slave  - Windows7
java 1.8.0_121"

I get exception after upgrading Allure Jenkins plugin to 2.11 when try to open generated report for test that was running on jenkins Slave on Windows7
`
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:120)
	at ru.yandex.qatools.allure.jenkins.AllureReportBuildAction$ArchiveReportBrowser.generateResponse(AllureReportBuildAction.java:85)
	at org.kohsuke.stapler.HttpResponseRenderer$Default.handleHttpResponse(HttpResponseRenderer.java:124)
	at org.kohsuke.stapler.HttpResponseRenderer$Default.generateResponse(HttpResponseRenderer.java:69)
	at org.kohsuke.stapler.Function.renderResponse(Function.java:127)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:110)
	at org.kohsuke.stapler.MetaClass$11.dispatch(MetaClass.java:385)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:362)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:362)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:236)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:236)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
	at com.smartcodeltd.jenkinsci.plugin.assetbundler.filters.LessCSS.doFilter(LessCSS.java:47)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:126)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:86)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

### PR DESCRIPTION
**Pull request by ehborisov**

### CODE REVIEW

File: src/main/java/ru/yandex/qatools/allure/jenkins/AllureReportPublisher.java [hunk 1]
```diff
@@ -190,6 +202,47 @@ private void generateReport(@Nonnull List<FilePath> resultsPaths, @Nonnull Run<?
         }
     }
 
+    private void waitForAllureReportChecksum(final FilePath reportArchive, final Run<?, ?> run,
+                                             final TaskListener listener, final Launcher launcher) throws IOException,
+            InterruptedException {
+        try {
+            final MessageDigest sha1 = MessageDigest.getInstance("SHA-1");
```
Comment (baev) [inline src/main/java/ru/yandex/qatools/allure/jenkins/AllureReportPublisher.java]: move this line to separate method

File: src/main/java/ru/yandex/qatools/allure/jenkins/AllureReportPublisher.java [hunk 2]
```diff
@@ -190,6 +202,47 @@ private void generateReport(@Nonnull List<FilePath> resultsPaths, @Nonnull Run<?
...
+    private static byte[] getReportFileBytes(final Launcher launcher, final FilePath reportPath) throws IOException {
+        try {
+            return launcher.getChannel().call(new MasterToSlaveCallable<byte[], Exception>() {
+                @Override
+                public byte[] call() throws Exception {
+                    return IOUtils.toByteArray(reportPath.toURI());
+                }
+            });
+        } catch (Exception e) {
+            throw new IOException(e);
```
Comment (baev) [inline src/main/java/ru/yandex/qatools/allure/jenkins/AllureReportPublisher.java]: WAT. Do you really want to wrap any exception to IO one

File: src/main/java/ru/yandex/qatools/allure/jenkins/AllureReportPublisher.java [hunk 3]
```diff
@@ -190,6 +202,47 @@ private void generateReport(@Nonnull List<FilePath> resultsPaths, @Nonnull Run<?
...
+                        @Override
+                        public boolean accept(File dir, String name) {
+                            return name.equals(REPORT_ARCHIVE_NAME);
+                        }
+                    });
+                    if (artifacts == null || artifacts.length == 0) {
+                        return false;
+                    }
+                    final File reportArtifact = artifacts[0];
+                    final byte[] actualSum = sha1.digest(IOUtils.toByteArray(reportArtifact.toURI()));
```
Comment (baev) [inline src/main/java/ru/yandex/qatools/allure/jenkins/AllureReportPublisher.java]: possible OOM in case of huge report

File: src/main/java/ru/yandex/qatools/allure/jenkins/AllureReportPublisher.java [hunk 4]
```diff
@@ -190,6 +202,47 @@ private void generateReport(@Nonnull List<FilePath> resultsPaths, @Nonnull Run<?
         }
     }
 
+    private void waitForAllureReportChecksum(final FilePath reportArchive, final Run<?, ?> run,
+                                             final TaskListener listener, final Launcher launcher) throws IOException,
+            InterruptedException {
+        try {
+            final MessageDigest sha1 = MessageDigest.getInstance("SHA-1");
+            final byte[] reportSum = sha1.digest(getReportFileBytes(launcher, reportArchive));
```
Comment (baev) [inline src/main/java/ru/yandex/qatools/allure/jenkins/AllureReportPublisher.java]: possible OOM in case of huge report

File: src/main/java/ru/yandex/qatools/allure/jenkins/AllureReportPublisher.java [hunk 5]
```diff
@@ -190,6 +202,45 @@ private void generateReport(@Nonnull List<FilePath> resultsPaths, @Nonnull Run<?
...
+                    @Override
+                    public boolean accept(File dir, String name) {
+                        return name.equals(REPORT_ARCHIVE_NAME);
+                    }
+                });
+                if (artifacts == null || artifacts.length == 0) {
+                    return false;
+                }
+                final File reportArtifact = artifacts[0];
+                final byte[] actualSum = FilePathUtils.computeSha1Sum(Files.newInputStream(reportArtifact.toPath()),
```
Comment (baev) [inline src/main/java/ru/yandex/qatools/allure/jenkins/AllureReportPublisher.java]: use try-with-resources to close the stream

File: src/main/java/ru/yandex/qatools/allure/jenkins/AllureReportPublisher.java [hunk 6]
```diff
@@ -190,6 +202,45 @@ private void generateReport(@Nonnull List<FilePath> resultsPaths, @Nonnull Run<?
...
+        });
+    }
+
+
+    private static byte[] getReportShaFromSlave(final Launcher launcher, final FilePath reportPath,
+                                                final TaskListener listener) throws IOException, InterruptedException {
+        return launcher.getChannel().call(new MasterToSlaveCallable<byte[], RuntimeException>() {
+            @Override
+            public byte[] call() {
+                final InputStream fileStream = getFileInputStream(reportPath, listener);
```
Comment (baev) [inline src/main/java/ru/yandex/qatools/allure/jenkins/AllureReportPublisher.java]: use try-with-resources to close the stream

File: src/main/java/ru/yandex/qatools/allure/jenkins/utils/FilePathUtils.java [hunk 7]
```diff
@@ -38,4 +44,34 @@ public static void deleteRecursive(FilePath filePath, PrintStream logger) {
...
+    public static InputStream getFileInputStream(final FilePath path, final TaskListener listener) {
+        try {
+            return path.read();
+        } catch (IOException | InterruptedException e) {
+            listener.getLogger().println("Unable to read file: " + e);
+        }
+        return null;
+    }
+
+    public static byte[] computeSha1Sum(final InputStream stream, final TaskListener listener) {
```
Comment (baev) [inline src/main/java/ru/yandex/qatools/allure/jenkins/utils/FilePathUtils.java]: this method should get `FilePath` as parameter, and return String. To get string representation of checksum use the following function:

```java
new BigInteger(1, bytes).toString(16) 
```

File: build.gradle [hunk 8]
```diff
@@ -91,6 +91,7 @@ dependencies {
     compile 'org.jenkins-ci.plugins:script-security:1.24@jar'
     compile 'org.jenkins-ci.main:jenkins-test-harness:2.15@jar'
     compile 'org.jenkins-ci.plugins:junit:1.2@jar'
+    compile 'com.jayway.awaitility:awaitility:1.7.0'
```
Comment (baev) [inline build.gradle]: use 'org.awaitility:awaitility:3.0.0' instead

File: src/main/java/ru/yandex/qatools/allure/jenkins/AllureReportPublisher.java [hunk 9]
```diff
@@ -56,6 +55,7 @@
 
     private static final String ALLURE_PREFIX = "allure";
     private static final String ALLURE_SUFFIX = "results";
+    private static final String REPORT_ARCHIVE_NAME = "allure-report.zip";
```
Comment (baev) [inline src/main/java/ru/yandex/qatools/allure/jenkins/AllureReportPublisher.java]: can we move this to plugin configuration?
